=== aditya-raghavan/webstack/celluloid/XML/movieschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/movieschema" 
xmlns:tns="http://www.example.org/movieschema" 
elementFormDefault="qualified">

<complexType name="infopagetype">
<sequence>
<element name="movie" type="tns:movietype" maxOccurs="unbounded"></element>
</sequence>
</complexType>
<complexType name="movietype">
<sequence>
<element name="moviename" type="string"></element>
<element name="year" type="integer"></element>
<element name="director" type="string"></element>
<element name="starring" type="string"></element>
<element name="rating" type="tns:ratingtype"></element>
<element name="plot" type="string"></element>

</sequence>
<attribute name="mid" type="ID" use="required"></attribute>
</complexType>
<simpleType name="ratingtype">
<restriction base="decimal">
<minInclusive value="0.0"></minInclusive>
<maxInclusive value="5.0"></maxInclusive>
</restriction>
</simpleType>

<element name="globalmovie" type="tns:infopagetype"></element>


</schema>

=== aditya-raghavan/webstack/celluloid/XML/movieinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="movieinfo.xsl"?>
<tns:globalmovie xmlns:tns="http://www.example.org/movieschema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/movieschema movieschema.xsd ">
  <tns:movie mid="A01">
    <tns:moviename>The Godfather</tns:moviename>
    <tns:year>1971</tns:year>
    <tns:director>Francis Ford Coppola</tns:director>
    <tns:starring>Marlon Brando, Al Pacino</tns:starring>
    <tns:rating>4.5</tns:rating>
    <tns:plot>The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.</tns:plot>
  </tns:movie>
  
  <tns:movie mid="A02">
    <tns:moviename>Once Upon a Time In Hollywood</tns:moviename>
    <tns:year>2019</tns:year>
    <tns:director> Quentin Tarantino</tns:director>
    <tns:starring> Leonardo DiCaprio, Brad Pitt</tns:starring>
    <tns:rating>4.0</tns:rating>
    <tns:plot>A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.</tns:plot>
  </tns:movie>
  
  <tns:movie mid="A03">
    <tns:moviename>1917</tns:moviename>
    <tns:year>2019</tns:year>
    <tns:director>Sam Mendes</tns:director>
    <tns:starring>Dean-Charles Chapman, George MacKay</tns:starring>
    <tns:rating>4.1</tns:rating>
    <tns:plot>April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.</tns:plot>
  </tns:movie>
  
  <tns:movie mid="A04">
    <tns:moviename>Jojo Rabbit</tns:moviename>
    <tns:year>2019</tns:year>
    <tns:director> Taika Waititi</tns:director>
    <tns:starring>Roman Griffin Davis, Thomasin McKenzie</tns:starring>
    <tns:rating>4.0</tns:rating>
    <tns:plot>A young boy in Hitler's army finds out his mother is hiding a Jewish girl in their home.</tns:plot>
  </tns:movie>
  
  <tns:movie mid="A05">
    <tns:moviename>12 Angry Men</tns:moviename>
    <tns:year>1957</tns:year>
    <tns:director>Sidney Lumet</tns:director>
    <tns:starring> Henry Fonda, Lee J. Cobb</tns:starring>
    <tns:rating>4.2</tns:rating>
    <tns:plot>A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.</tns:plot>
  </tns:movie>
  
  <tns:movie mid="A06">
    <tns:moviename>Interstellar</tns:moviename>
    <tns:year>2014</tns:year>
    <tns:director> Christopher Nolan</tns:director>
    <tns:starring>Matthew McConaughey, Anne Hathaway</tns:starring>
    <tns:rating>4.4</tns:rating>
    <tns:plot>A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.</tns:plot>
  </tns:movie>
</tns:globalmovie>
