=== aditya-raghavan/webstack/Emp/emp_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<emp:schema xmlns:emp="http://www.w3.org/2001/XMLSchema" xmlns:Q1="tns">

<emp:complexType name="companytype">
<emp:sequence>
<emp:element name="employee" type="employeetype" maxOccurs="unbounded"></emp:element>
</emp:sequence>

</emp:complexType>

<emp:complexType name="employeetype">
<emp:sequence>
<emp:element name="Emp-name" type="emp:string"></emp:element>
<emp:element name="Emp-age" type ="emp:integer"></emp:element>
<emp:element name="Emp-salary" type="salarytype"></emp:element>
<emp:element name="Emp-emailid" type ="emp:string"></emp:element>
<emp:element name="Emp-phonenum" type="emp:integer"></emp:element>
<emp:element name="Emp-designation" type ="emp:string"></emp:element>
</emp:sequence>
<emp:attribute name="id" type="emp:ID" use="required"></emp:attribute>
</emp:complexType>

<emp:simpleType name="salarytype">
<emp:restriction base="emp:integer">
<emp:minInclusive value="50000"></emp:minInclusive>
<emp:maxInclusive value="200000"></emp:maxInclusive>
</emp:restriction>
</emp:simpleType>

<emp:element name="company" type="companytype"></emp:element>



</emp:schema>

=== aditya-raghavan/webstack/Emp/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="emp_style.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emp_schema.xsd">
  <employee id="A01">
    <Emp-name>Jackson</Emp-name>
    <Emp-age>55</Emp-age>
    <Emp-salary>80000</Emp-salary>
    <Emp-emailid>jackson@gmail.com</Emp-emailid>
    <Emp-phonenum>1234567890</Emp-phonenum>
    <Emp-designation>Manager</Emp-designation>
  </employee>
  
  <employee id="A02">
    <Emp-name>Mike</Emp-name>
    <Emp-age>44</Emp-age>
    <Emp-salary>100000</Emp-salary>
    <Emp-emailid>mike@gmail.com</Emp-emailid>
    <Emp-phonenum>2345678910</Emp-phonenum>
    <Emp-designation>Senior Devoloper</Emp-designation>
  </employee>
  
  <employee id="A03">
    <Emp-name>Percy</Emp-name>
    <Emp-age>30</Emp-age>
    <Emp-salary>120000</Emp-salary>
    <Emp-emailid>percy@gmail.com</Emp-emailid>
    <Emp-phonenum>2334599876</Emp-phonenum>
    <Emp-designation>Analyst</Emp-designation>
  </employee>
  
  <employee id="A04">
    <Emp-name>Hannah</Emp-name>
    <Emp-age>24</Emp-age>
    <Emp-salary>90000</Emp-salary>
    <Emp-emailid>hannah@gmail.com</Emp-emailid>
    <Emp-phonenum>3334588890</Emp-phonenum>
    <Emp-designation>HR</Emp-designation>
  </employee>
  
  <employee id="A05">
    <Emp-name>Hailey</Emp-name>
    <Emp-age>45</Emp-age>
    <Emp-salary>150000</Emp-salary>
    <Emp-emailid>hailey@gmail.com</Emp-emailid>
    <Emp-phonenum>4909023875</Emp-phonenum>
    <Emp-designation>Senior Analyst</Emp-designation>
  </employee>
  
  <employee id="A06">
    <Emp-name>Monty</Emp-name>
    <Emp-age>35</Emp-age>
    <Emp-salary>190000</Emp-salary>
    <Emp-emailid>monty@gmail.com</Emp-emailid>
    <Emp-phonenum>3939393939</Emp-phonenum>
    <Emp-designation>General Manager</Emp-designation>
  </employee>
</company>
